wrtp/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :resources
  resources :beliefs
  resources :issues

  root 'issues#index'

end

wrtp/app/models/belief.rb
class Belief < ActiveRecord::Base
  # Associations
  belongs_to :issue

  # Validations
  validates :title, :summary, :explanation, presence: true
end

wrtp/app/models/issue.rb
class Issue < ActiveRecord::Base
  # Associations
  has_many :beliefs

  # Validations
  validates :name, :summary, presence: true

  validates_associated :beliefs
end

wrtp/app/models/resource.rb
class Resource < ActiveRecord::Base
  validates :name, :description, :url, presence: true
end

wrtp/app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

wrtp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

wrtp/app/controllers/beliefs_controller.rb
class BeliefsController < ApplicationController
  before_action :set_belief, only: [:show, :edit, :update, :destroy]

  # GET /beliefs
  # GET /beliefs.json
  def index
    @beliefs = Belief.all
  end

  # GET /beliefs/1
  # GET /beliefs/1.json
  def show
  end

  # GET /beliefs/new
  def new
    @belief = Belief.new
  end

  # GET /beliefs/1/edit
  def edit
  end

  # POST /beliefs
  # POST /beliefs.json
  def create
    @belief = Belief.new(belief_params)

    respond_to do |format|
      if @belief.save
        format.html { redirect_to @belief, notice: 'Belief was successfully created.' }
        format.json { render :show, status: :created, location: @belief }
      else
        format.html { render :new }
        format.json { render json: @belief.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beliefs/1
  # PATCH/PUT /beliefs/1.json
  def update
    respond_to do |format|
      if @belief.update(belief_params)
        format.html { redirect_to @belief, notice: 'Belief was successfully updated.' }
        format.json { render :show, status: :ok, location: @belief }
      else
        format.html { render :edit }
        format.json { render json: @belief.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beliefs/1
  # DELETE /beliefs/1.json
  def destroy
    @belief.destroy
    respond_to do |format|
      format.html { redirect_to beliefs_url, notice: 'Belief was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_belief
      @belief = Belief.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def belief_params
      params.require(:belief).permit(:title, :summary, :explanation, :score)
    end
end

wrtp/app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :update, :destroy]

  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue.all
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(issue_params)

    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url, notice: 'Issue was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:name, :summary, :score, :integer)
    end
end

wrtp/app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  before_action :set_resource, only: [:show, :edit, :update, :destroy]

  # GET /resources
  # GET /resources.json
  def index
    @resources = Resource.all
  end

  # GET /resources/1
  # GET /resources/1.json
  def show
  end

  # GET /resources/new
  def new
    @resource = Resource.new
  end

  # GET /resources/1/edit
  def edit
  end

  # POST /resources
  # POST /resources.json
  def create
    @resource = Resource.new(resource_params)

    respond_to do |format|
      if @resource.save
        format.html { redirect_to @resource, notice: 'Resource was successfully created.' }
        format.json { render :show, status: :created, location: @resource }
      else
        format.html { render :new }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resources/1
  # PATCH/PUT /resources/1.json
  def update
    respond_to do |format|
      if @resource.update(resource_params)
        format.html { redirect_to @resource, notice: 'Resource was successfully updated.' }
        format.json { render :show, status: :ok, location: @resource }
      else
        format.html { render :edit }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resources/1
  # DELETE /resources/1.json
  def destroy
    @resource.destroy
    respond_to do |format|
      format.html { redirect_to resources_url, notice: 'Resource was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resource
      @resource = Resource.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resource_params
      params.require(:resource).permit(:name, :description, :url, :published)
    end
end

wrtp/app/helpers/application_helper.rb
module ApplicationHelper
end

wrtp/app/helpers/beliefs_helper.rb
module BeliefsHelper
end

wrtp/app/helpers/issues_helper.rb
module IssuesHelper
end

wrtp/app/helpers/resources_helper.rb
module ResourcesHelper
end

wrtp/app/views/beliefs/_form.html.erb
<%= simple_form_for(@belief) do |f| %>
  <% if @belief.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@belief.errors.count, "error") %> prohibited this belief from being saved:</h2>

      <ul>
      <% @belief.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :issue, for: 'belief_issue_id' %><br>
    <%= f.association :issue, include_blank: false, label: false %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_area :summary %>
  </div>
  <div class="field">
    <%= f.label :explanation %><br>
    <%= f.text_area :explanation %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

wrtp/app/views/beliefs/edit.html.erb
<h1>Editing Belief</h1>

<%= render 'form' %>

<%= link_to 'Show', @belief %> |
<%= link_to 'Back', beliefs_path %>

wrtp/app/views/beliefs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Beliefs</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @beliefs.each do |belief| %>
      <tr>
        <td><%= belief.id %></td>
        <td><%= belief.title %></td>
        <td><%= belief.score %></td>
        <td><%= link_to 'Show', belief %></td>
        <td><%= link_to 'Edit', edit_belief_path(belief) %></td>
        <td><%= link_to 'Destroy', belief, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Belief', new_belief_path %>

wrtp/app/views/beliefs/new.html.erb
<h1>New Belief</h1>

<%= render 'form' %>

<%= link_to 'Back', beliefs_path %>

wrtp/app/views/beliefs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @belief.title %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @belief.summary %>
</p>

<p>
  <strong>Explanation:</strong>
  <%= @belief.explanation %>
</p>

<p>
  <strong>Score:</strong>
  <%= @belief.score %>
</p>

<%= link_to 'Edit', edit_belief_path(@belief) %> |
<%= link_to 'Back', beliefs_path %>

wrtp/app/views/issues/_form.html.erb
<%= form_for(@issue) do |f| %>
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% @issue.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_area :summary %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.text_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

wrtp/app/views/issues/edit.html.erb
<h1>Editing Issue</h1>

<%= render 'form' %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

wrtp/app/views/issues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Issues</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Summary</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        <td><%= issue.name %></td>
        <td><%= issue.summary %></td>
        <td><%= issue.score %></td>
        <td><%= link_to 'Show', issue %></td>
        <td><%= link_to 'Edit', edit_issue_path(issue) %></td>
        <td><%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Issue', new_issue_path %>

wrtp/app/views/issues/new.html.erb
<h1>New Issue</h1>

<%= render 'form' %>

<%= link_to 'Back', issues_path %>

wrtp/app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @issue.name %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @issue.summary %>
</p>

<p>
  <strong>Score:</strong>
  <%= @issue.score %>
</p>

<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Back', issues_path %>

wrtp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wrtp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>
</body>
</html>

wrtp/app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :published %><br>
    <%= f.check_box :published %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

wrtp/app/views/resources/edit.html.erb
<h1>Editing Resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

wrtp/app/views/resources/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Resources</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Url</th>
      <th>Published</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= resource.name %></td>
        <td><%= resource.description %></td>
        <td><%= resource.url %></td>
        <td><%= resource.published %></td>
        <td><%= link_to 'Show', resource %></td>
        <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
        <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resource', new_resource_path %>

wrtp/app/views/resources/new.html.erb
<h1>New Resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

wrtp/app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @resource.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @resource.description %>
</p>

<p>
  <strong>Url:</strong>
  <%= @resource.url %>
</p>

<p>
  <strong>Published:</strong>
  <%= @resource.published %>
</p>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>